apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: c1
      image: polinux/stress
      # 优先使用本地镜像
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1" ,"--vm-bytes","150m" ,"--vm-hang","1"]

# polinux/stress 这个镜像用于压力测试
