apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:

  containers:
    - name: c1
      image: polinux/stress
      # 优先使用本地镜像
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      # 产生一个进程分配好 300M内存，1秒后释放
      args: ["--vm", "1" ,"--vm-bytes","300m" ,"--vm-hang","1"]
    - name: c2
      image: polinux/stress
      # 优先使用本地镜像
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: [ "stress" ]
      # 产生一个进程分配好 300M内存，1秒后释放
      args: [ "--vm", "1" ,"--vm-bytes","300m" ,"--vm-hang","1" ]

# polinux/stress 这个镜像用于压力测试
