apiVersion: v1    #必选： API版本号
kind: Pod         #必选： pod
metadata:           #必选： 元数据
  name: string        #必选：pod名称
  namespace: string   #pod所属的命名空间，默认为 default
  labels:             #自定义标签
    role: string         #自定义标签名称/值
    role2: string        #自定义标签名称/值
  annotations:
    name: string      #自定义注释列表
spec:
  containers:
    - name: title
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: title
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  