apiVersion: v1
kind: Pod
metadata:
  name: pod-stress
spec:
  containers:
    - name: c1
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1" ,"--vm-bytes","150m" ,"--vm-hang","1"]

# polinux/stress 这个镜像用于压力测试
