apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
        - name: pi
          image: perl
          imagePullPolicy: IfNotPresent
          command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
      restartPolicy: Never  # 执行完不在重启
