apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.10-192.168.4.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool  # 关联你定义的 IP 池名称
