apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: myapp